### ISSUE TITLE
Error: Shell class PhpunitShell could not be found.

### ISSUE THREAD

**Issue by Skeletoneyes** [Hyra/PHPUnit-Cake2#4]
I copied the PhpunitShell to `cake_php/app/Console/Command/PhpunitShell.php` and then ran `cake phpunit install` and received:

Error: Shell class PhpunitShell could not be found.

Googled around and found little support on how to resolve this issue, any pointers?

Thanks in advance!

**Comment by dereuromark** [comment]
Try me plugin version https://github.com/dereuromark/PHPUnit-Cake2 and run `Phpunit.Phpunit install`

also make sure you got `CakePlugin::loadAll()` (or specifically `Phpunit`) in your bootstrap.

**Comment by Hyra** [comment]
Enabling the CakePlugin::loadAll() or CakePlugin::load('Phpunit') should fix it.

If not, re-open the issue :)
