### ISSUE TITLE
Error: Failed opening required 'PHPUnit/Framework/MockObject/Autoload.php'

### ISSUE THREAD

**Issue by zawzaw** [Hyra/PHPUnit-Cake2#6]
I installed Phpunit successfully. But when I run test.php in browser, I hit the error. 

"require_once(PHPUnit/Framework/MockObject/Autoload.php)". 

I tried ways to solve it but failed. I am using cakephp 2.1.0. Any advice? 

Thanks in advance.

**Comment by Hyra** [comment]
I ran into that issue once or twice on a machine ..

You could prefix the require_once statements with APP and the desitination you installed it to (plugin or vendors) .. which should fix the error.

The files you want to look for are the Autoload.php files

I can probably prefix them in those files in a later version.

**Comment by zawzaw** [comment]
Thanks for reply Hyra! I manage to find MockObject folder in previously-installed PHPUnit and copy it into the vendors folders. Then resolved. :)

**Comment by Hyra** [comment]
Awesome :)

**Comment by divyanshu-das** [comment]
I got the same issue today. That folder has been removed from phpunit.

Just comment out the require statement. It works.

**Comment by Hyra** [comment]
Thanks for the suggestion, I'll have a look.

**Comment by saturday** [comment]
This is still an issue. I've commented out the offending line; however it certainly isn't obvious that the MockObject autoload.php file is no longer needed and that we can just comment out line 71.
